package com.thlh.baselib.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.thlh.baselib.model.Cartgoods;
import com.thlh.baselib.model.GoodsDb;
import com.thlh.baselib.model.LogsOrder;
import com.thlh.baselib.model.Seengood;
import com.thlh.baselib.model.Supplier;

import com.thlh.baselib.db.CartgoodsDao;
import com.thlh.baselib.db.GoodsDbDao;
import com.thlh.baselib.db.LogsOrderDao;
import com.thlh.baselib.db.SeengoodDao;
import com.thlh.baselib.db.SupplierDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cartgoodsDaoConfig;
    private final DaoConfig goodsDbDaoConfig;
    private final DaoConfig logsOrderDaoConfig;
    private final DaoConfig seengoodDaoConfig;
    private final DaoConfig supplierDaoConfig;

    private final CartgoodsDao cartgoodsDao;
    private final GoodsDbDao goodsDbDao;
    private final LogsOrderDao logsOrderDao;
    private final SeengoodDao seengoodDao;
    private final SupplierDao supplierDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cartgoodsDaoConfig = daoConfigMap.get(CartgoodsDao.class).clone();
        cartgoodsDaoConfig.initIdentityScope(type);

        goodsDbDaoConfig = daoConfigMap.get(GoodsDbDao.class).clone();
        goodsDbDaoConfig.initIdentityScope(type);

        logsOrderDaoConfig = daoConfigMap.get(LogsOrderDao.class).clone();
        logsOrderDaoConfig.initIdentityScope(type);

        seengoodDaoConfig = daoConfigMap.get(SeengoodDao.class).clone();
        seengoodDaoConfig.initIdentityScope(type);

        supplierDaoConfig = daoConfigMap.get(SupplierDao.class).clone();
        supplierDaoConfig.initIdentityScope(type);

        cartgoodsDao = new CartgoodsDao(cartgoodsDaoConfig, this);
        goodsDbDao = new GoodsDbDao(goodsDbDaoConfig, this);
        logsOrderDao = new LogsOrderDao(logsOrderDaoConfig, this);
        seengoodDao = new SeengoodDao(seengoodDaoConfig, this);
        supplierDao = new SupplierDao(supplierDaoConfig, this);

        registerDao(Cartgoods.class, cartgoodsDao);
        registerDao(GoodsDb.class, goodsDbDao);
        registerDao(LogsOrder.class, logsOrderDao);
        registerDao(Seengood.class, seengoodDao);
        registerDao(Supplier.class, supplierDao);
    }
    
    public void clear() {
        cartgoodsDaoConfig.clearIdentityScope();
        goodsDbDaoConfig.clearIdentityScope();
        logsOrderDaoConfig.clearIdentityScope();
        seengoodDaoConfig.clearIdentityScope();
        supplierDaoConfig.clearIdentityScope();
    }

    public CartgoodsDao getCartgoodsDao() {
        return cartgoodsDao;
    }

    public GoodsDbDao getGoodsDbDao() {
        return goodsDbDao;
    }

    public LogsOrderDao getLogsOrderDao() {
        return logsOrderDao;
    }

    public SeengoodDao getSeengoodDao() {
        return seengoodDao;
    }

    public SupplierDao getSupplierDao() {
        return supplierDao;
    }

}
