package com.thlh.baselib.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import java.util.List;

/**
 * Entity mapped to table "GOODS".
 */
public class GoodsCollect extends  Goods{

    private List<GoodsDetailProperty> spec;
}
